### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by CrayyanG** [1c7/Fitness#1]
你好 训练太频繁会导致肌肉紧绷 你平时会选择什么样的放松方式？
我觉得每月做一次盲人按摩会不错，广州你有推荐的吗

**Comment by 1c7** [comment]
自我放松：泡沫轴，筋膜球，筋膜枪。
盲人按摩我没试过。
健身房里的"运动康复课"也是"按摩"，就是有点贵。

> 我觉得每月做一次盲人按摩会不错，广州你有推荐的吗

无推荐。


我也是学习状态，暂时做不了什么有用的分享，建议抖音和B站评论区看看
